/**
 * Submit a validator deposit to the Zond beacon chain deposit contract
 *
 * This script reads deposit_data.json generated by staking-deposit-cli
 * and submits it to the deposit contract.
 *
 * WARNING: This will transfer 40,000 QRL to the deposit contract.
 * This is irreversible until validator withdrawal is implemented.
 */

const path = require('path');
const fs = require('fs');

require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const { Web3 } = require('@theqrl/web3');
const { MnemonicToSeedBin } = require('@theqrl/wallet.js');

const config = require('../config/testnet.json');

// Deposit contract address
const DEPOSIT_CONTRACT_ADDRESS = 'Z4242424242424242424242424242424242424242';

// Validator stake amount (40,000 QRL in wei)
const VALIDATOR_STAKE = BigInt('40000000000000000000000');

function loadArtifact(name) {
    const artifactPath = path.join(__dirname, '..', 'artifacts', `${name}.json`);
    if (!fs.existsSync(artifactPath)) {
        throw new Error(`Artifact not found: ${artifactPath}`);
    }
    return JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
}

function loadDepositData(folder = 'validator_keys') {
    const files = fs.readdirSync(folder);
    const depositFile = files.find(f => f.startsWith('deposit_data-'));
    if (!depositFile) {
        throw new Error(`No deposit_data file found in ${folder}`);
    }
    const depositPath = path.join(folder, depositFile);
    const data = JSON.parse(fs.readFileSync(depositPath, 'utf8'));
    return data[0]; // Return first deposit
}

async function estimateGasWithBuffer(web3, txParams) {
    const estimated = await web3.zond.estimateGas(txParams);
    // Add 50% buffer for complex deposit transaction
    return BigInt(estimated) * 150n / 100n;
}

async function submitDeposit() {
    // Validate environment - prefer WHALE_SEED for large deposits
    const seedEnvVar = process.env.WHALE_SEED ? 'WHALE_SEED' : 'TESTNET_SEED';
    const mnemonic = process.env[seedEnvVar];
    if (!mnemonic) {
        throw new Error('WHALE_SEED or TESTNET_SEED environment variable is required');
    }

    const web3 = new Web3(config.provider);
    const depositAbi = loadArtifact('DepositContract').abi;

    // Setup account from seed
    console.log(`Using ${seedEnvVar} for deposit`);
    const seedBin = MnemonicToSeedBin(mnemonic);
    const seedHex = '0x' + Buffer.from(seedBin).toString('hex');
    const account = web3.zond.accounts.seedToAccount(seedHex);
    web3.zond.accounts.wallet.add(account);

    console.log('=== Beacon Chain Deposit Submission ===\n');
    console.log('Account:', account.address);

    // Check balance
    const balance = await web3.zond.getBalance(account.address);
    console.log('Balance:', web3.utils.fromWei(balance.toString(), 'ether'), 'QRL');

    if (BigInt(balance) < VALIDATOR_STAKE) {
        throw new Error(`Insufficient balance. Need ${web3.utils.fromWei(VALIDATOR_STAKE.toString(), 'ether')} QRL`);
    }

    // Load deposit data
    console.log('\nLoading deposit data...');
    const depositData = loadDepositData();

    console.log('Pubkey:', depositData.pubkey.slice(0, 40) + '...');
    console.log('Amount:', depositData.amount / 1e9, 'QRL');
    console.log('Withdrawal credentials:', depositData.withdrawal_credentials);
    console.log('Deposit data root:', depositData.deposit_data_root);

    // Create contract instance
    const depositContract = new web3.zond.Contract(depositAbi, DEPOSIT_CONTRACT_ADDRESS);

    // Prepare deposit parameters
    const pubkey = depositData.pubkey;
    const withdrawalCredentials = depositData.withdrawal_credentials;
    const signature = depositData.signature;
    const depositDataRoot = depositData.deposit_data_root;

    console.log('\nPubkey length:', (pubkey.length - 2) / 2, 'bytes');
    console.log('Signature length:', (signature.length - 2) / 2, 'bytes');

    // Confirm before proceeding
    console.log('\n====================================');
    console.log('WARNING: This will stake 40,000 QRL!');
    console.log('This is IRREVERSIBLE until withdrawal is supported.');
    console.log('====================================\n');

    // Check for --confirm flag
    if (!process.argv.includes('--confirm')) {
        console.log('Add --confirm flag to proceed with deposit.');
        console.log('\nExample: node scripts/submit-deposit.js --confirm');
        return;
    }

    console.log('Submitting deposit...');

    try {
        // Encode function call
        const depositCallData = depositContract.methods.deposit(
            pubkey,
            withdrawalCredentials,
            signature,
            depositDataRoot
        ).encodeABI();

        // Estimate gas
        const txParams = {
            from: account.address,
            to: DEPOSIT_CONTRACT_ADDRESS,
            data: depositCallData,
            value: VALIDATOR_STAKE.toString()
        };

        const gasEstimate = await estimateGasWithBuffer(web3, txParams);
        console.log('Gas estimate:', gasEstimate.toString());

        // Submit transaction
        const tx = await web3.zond.sendTransaction({
            ...txParams,
            gas: gasEstimate.toString()
        });

        console.log('\nDeposit submitted successfully!');
        console.log('Transaction hash:', tx.transactionHash);
        console.log('Block number:', tx.blockNumber);

        // Verify deposit count increased
        const depositCount = await depositContract.methods.get_deposit_count().call();
        const countBuffer = Buffer.from(depositCount.slice(2), 'hex');
        let count = 0n;
        for (let i = 0; i < countBuffer.length; i++) {
            count += BigInt(countBuffer[i]) << BigInt(i * 8);
        }
        console.log('\nNew deposit count:', count.toString());

    } catch (err) {
        console.error('\nDeposit failed:', err.message);
        throw err;
    }
}

submitDeposit().catch(err => {
    console.error('Error:', err.message);
    process.exit(1);
});
